{
 "title": "Day2_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hostnames",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device-model" ], "type": "tag" },
      { "params": [ "host-name" ], "type": "tag" },
      { "params": [ "site-id" ], "type": "tag" },
      { "params": [ "system-ip" ], "type": "tag" }
     ],
     "measurement": "monitor",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Usernames",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "username" ], "type": "tag" }
     ],
     "measurement": "usernames",
     "select": [
      [
       { "params": [ "fullname" ], "type": "field" }
      ],
      [
       { "params": [ "group" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TX Interface Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "aggregation",
     "select": [
      [
       { "params": [ "tx_pkts" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RX Interface Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "aggregation",
     "select": [
      [
       { "params": [ "rx_pkts" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TX Interface Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "aggregation",
     "select": [
      [
       { "params": [ "tx_drops" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RX Interface Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "aggregation",
     "select": [
      [
       { "params": [ "rx_drops" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}